Feature/ Event details 탭 하단에 기타 Information 표시
boostcamp-2020/Project11-A-Web-FE-Performance-Monitoring-Admin pull request #24
Opened 2020-12-08 05:25 UTC by Eunbin-Kim

### Issue Number
Close #

### 변경사항

### 새로운 기능

- event details 탭에서 event 관련 추가 정보들 하단에 표시 (하단 sentry 이미지  참고)
![image](https://user-images.githubusercontent.com/37240495/101443564-11500580-3961-11eb-8468-5f08b48c2521.png)

### 작업 유형
- [x] 신규 기능 추가
- [ ] 버그 수정
- [ ] 리펙토링
- [ ] 문서 업데이트

### 체크리스트
- [x] Merge 하는 브랜치가 올바른가?
- [x] 코딩컨벤션을 준수하는가?
- [x] PR과 관련없는 변경사항이 없는가?
- [x] 내 코드에 대한 자기 검토가 되었는가?
- [ ] 변경사항이 효과적이거나 동작이 작동한다는 것을 보증하는 테스트를 추가하였는가?
- [ ] 새로운 테스트와 기존의 테스트가 변경사항에 대해 만족하는가?

2020-12-08 14:11 UTC, gitdog01 approved these changes
고생하셨습니다.

2020-12-08 14:11 UTC, gitdog01 commented on src/pages/Issue/components/Details/ErrorStack/StackContext.tsx
> +    fontSize: 12,
디테일 ㄷㄷ

2020-12-09 09:35 UTC, Kangsukmin approved these changes
수고하셨습니다!

2020-12-09 09:35 UTC, maong0927 requested changes
고생하셨습니다!!

2020-12-09 10:04 UTC, maong0927 approved these changes

2020-12-09 10:30 UTC, merged